// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PedidosService.Data;

#nullable disable

namespace PedidosService.Migrations
{
    [DbContext(typeof(PedidosDbContext))]
    [Migration("20250111202949_AtualizarPedidosDbContext")]
    partial class AtualizarPedidosDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PedidosService.Model.ItemPedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedidoid");

                    b.Property<string>("Produto")
                        .HasColumnType("text")
                        .HasColumnName("produto");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("preco");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.HasKey("PedidoId", "Produto");

                    b.ToTable("itenspedido", (string)null);
                });

            modelBuilder.Entity("PedidosService.Model.Pedido", b =>
                {
                    b.Property<int>("CodigoPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("codigo_pedido");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodigoPedido"));

                    b.Property<int>("CodigoCliente")
                        .HasColumnType("integer")
                        .HasColumnName("codigo_cliente");

                    b.HasKey("CodigoPedido");

                    b.ToTable("pedidos", (string)null);
                });

            modelBuilder.Entity("PedidosService.Model.ItemPedido", b =>
                {
                    b.HasOne("PedidosService.Model.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("PedidosService.Model.Pedido", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
