CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE pedidos (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    codigo_pedido integer NOT NULL,
    codigo_cliente integer NOT NULL,
    CONSTRAINT "PK_pedidos" PRIMARY KEY ("Id")
);

CREATE TABLE itenspedido (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PedidoId" integer NOT NULL,
    produto text NOT NULL,
    quantidade integer NOT NULL,
    preco numeric(10,2) NOT NULL,
    CONSTRAINT "PK_itenspedido" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_itenspedido_pedidos_PedidoId" FOREIGN KEY ("PedidoId") REFERENCES pedidos ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_itenspedido_PedidoId" ON itenspedido ("PedidoId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250110233511_CriarBancoPedidos', '9.0.0');

ALTER TABLE itenspedido DROP CONSTRAINT "PK_itenspedido";

DROP INDEX "IX_itenspedido_PedidoId";

ALTER TABLE itenspedido DROP COLUMN "Id";

ALTER TABLE itenspedido ADD CONSTRAINT "PK_itenspedido" PRIMARY KEY ("PedidoId", produto);

CREATE UNIQUE INDEX "IX_pedidos_codigo_cliente" ON pedidos (codigo_cliente);

CREATE UNIQUE INDEX "IX_pedidos_codigo_pedido" ON pedidos (codigo_pedido);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250111190453_AtualizarPedidos', '9.0.0');

DROP INDEX "IX_pedidos_codigo_cliente";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250111193059_RemoverIndiceUnicoCliente', '9.0.0');

DROP INDEX "IX_pedidos_codigo_pedido";

CREATE INDEX "IX_pedidos_codigo_pedido" ON pedidos (codigo_pedido);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250111193400_PermitirMultiplosPedidosPorCliente', '9.0.0');

DROP INDEX "IX_pedidos_codigo_pedido";

CREATE UNIQUE INDEX "IX_pedidos_codigo_pedido_codigo_cliente" ON pedidos (codigo_pedido, codigo_cliente);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250111194417_IndiceUnicoCodigoPedidoCliente', '9.0.0');

CREATE UNIQUE INDEX "IX_pedidos_codigo_pedido" ON pedidos (codigo_pedido);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250111195225_UnicidadeCodigoPedido', '9.0.0');

ALTER TABLE itenspedido DROP CONSTRAINT "FK_itenspedido_pedidos_PedidoId";

ALTER TABLE itenspedido RENAME COLUMN "PedidoId" TO pedidoid;

ALTER TABLE pedidos ALTER COLUMN codigo_pedido DROP DEFAULT;
ALTER TABLE pedidos ALTER COLUMN codigo_pedido ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE itenspedido ADD CONSTRAINT "FK_itenspedido_pedidos_pedidoid" FOREIGN KEY (pedidoid) REFERENCES pedidos (codigo_pedido) ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250111202949_AtualizarPedidosDbContext', '9.0.0');

ALTER TABLE itenspedido DROP CONSTRAINT "FK_itenspedido_pedidos_pedidoid";

ALTER TABLE itenspedido RENAME COLUMN pedidoid TO pedido_id;

ALTER TABLE itenspedido ADD CONSTRAINT "FK_itenspedido_pedidos_pedido_id" FOREIGN KEY (pedido_id) REFERENCES pedidos (codigo_pedido) ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250111204626_CodigoPedidoAutoIncremental', '9.0.0');

COMMIT;

